FROM node:18-alpine

WORKDIR /app

COPY DatabaseMicroservice/package*.json ./

RUN echo "List content in /app" && pwd && ls -la

RUN npm i

COPY DatabaseMicroservice/. .

EXPOSE 3001

CMD ["npm", "run", "watch"]
